### ISSUE TITLE
Information is leaking

### ISSUE THREAD

**Issue by cm39fkbm** [algorithm-ssau/electronics-store#37]
id
:
607adb7363e36f27103487f4
customer_name
:
"Корчагин Петр Петрович"
email
:
"korchagin_official@yahoo.com"
login
:
"Sharp"
password
:
"12345"
account
:
2400
avatar_src
:
"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d627926d-e1b..."
order_ids
:
__v
:
0
verified
:
true
_id
:
607adb9763e36f27103487f5
customer_name
:
"Абрамов Кирилл Дмитриевич"
email
:
"abramoff@ya.ru"
login
:
"Abramoff"
password
:
"54321"
account
:
3222
avatar_src
:
"https://cs6.pikabu.ru/post_img/big/2014/11/15/8/1416058691_2050061048...."
order_ids
:
__v
:
0
_id
:
6087b2fe93aad40810ea10e9
customer_name
:
"Кротков Владимир Денисович"
email
:
"hexhummingbird@gmail.com"
login
:
"HexHummingbird"
password
:
"54321"
account
:
83650
avatar_src
:
"https://avatarfiles.alphacoders.com/177/thumb-177263.png"
order_ids
:
verified
:
true
__v
:
0
_id
:
6092ae86ce424c28f05e59b2
customer_name
:
"Иванов Сергей Юрьевич"
email
:
"richserj@gmail.com"
login
:
"richserj"
password
:
"serega"
account
:
100
avatar_src
:
"https://i.pinimg.com/originals/e0/7d/06/e07d0688389b79d19a014fd12d9bea..."
order_ids
:
verified
:
false
__v
:
0
_id
:
609e654f60fe161c7cd665bb
customer_name
:
""
email
:
""
login
:
""
password
:
""
account
:
10000
avatar_src
:
""
order_ids
:
verified
:
false
__v
:
0
_id
:
609f9eb4f42996466b97f0e6
customer_name
:
""
email
:
""
login
:
""
password
:
""
account
:
10000
avatar_src
:
"https://media.wired.com/photos/5cdefb92b86e041493d389df/1:1/w_988,h_98..."
order_ids
:
verified
:
false
__v
:
0
_id
:
60a03db43ecbba50938c0dc3
customer_name
:
""
email
:
""
login
:
""
password
:
""
account
:
10000
avatar_src
:
"https://media.wired.com/photos/5cdefb92b86e041493d389df/1:1/w_988,h_98..."
order_ids
:
verified
:
false
__v
:
0
_id
:
60a03f713ecbba50938c0dc4
customer_name
:
""
email
:
""
login
:
""
password
:
""
account
:
10000
avatar_src
:
"https://media.wired.com/photos/5cdefb92b86e041493d389df/1:1/w_988,h_98..."
order_ids
:
verified
:
false
__v
:
0
_id
:
60a0e866a85f5a61e1d0219f
customer_name
:
""
email
:
""
login
:
""
password
:
""
account
:
10000
avatar_src
:
"https://media.wired.com/photos/5cdefb92b86e041493d389df/1:1/w_988,h_98..."
order_ids
:
verified
:
false
__v
:
0
_id
:
60a0e977a85f5a61e1d021a0
customer_name
:
"Джек"
email
:
"jack@gmail.com"
login
:
"Jack_999"
password
:
"qwe"
account
:
10000
avatar_src
:
""
order_ids
:
verified
:
false
__v
:
0
_id
:
60a0ea60a85f5a61e1d021a1
customer_name
:
"Олег"
email
:
"olezha@mail.ru"
login
:
"Olezha"
password
:
"999"
account
:
10000
avatar_src
:
""
order_ids
:
verified
:
false
__v
:
0
_id
:
60a14d52a85f5a61e1d021af
customer_name
:
"Чувак"
email
:
"chuvak@yandex.ru"
login
:
"Chuvak"
password
:
"1234567890"
account
:
10000
avatar_src
:
"https://sun9-59.userapi.com/c636619/v636619135/5bc34/xnFdMmDP7I0.jpg"
order_ids
:
verified
:
false
__v
:
0

Local
3 DBS
11 COLLECTIONS

 FAVORITE
HOSTS
cluster0-shard-00-01.3oxi7.mongodb.net:27017
cluster0-shard-00-02.3oxi7.mongodb.net:27017
cluster0-shard-00-00.3oxi7.mongodb.net:27017
CLUSTER
Replica Set (atlas-goe2hb-shard-0)
3 Nodes
EDITION
MongoDB 4.4.6 Enterprise
Filter your data
admin
electronics-store
customers 

orders 
products 
templates 
local
CREATE DATABASE

**Comment by HexHummingbird** [comment]
There was an accidental push of file that contains mongo db url. We know this is bad, but since the db contains and will contain fake information even after release, this is fine. We do not develop active security measures, because this project is not commercial and will never be. Thanks for noticing, though!
